#!/bin/sh

while :; do
    xsetroot -name "| $(brightnessctl g)/$(brightnessctl m) | B: $(awk '{print $4}' <<< $(acpi) | tr -d ',') ($(cat /sys/class/power_supply/BAT1/status | cut -c 1)) | VH: $(amixer -c 1 get Headphone | awk -F'[][]' 'END{ print $2 }') | VS: $(amixer -c 1 get Speaker | awk -F'[][]' 'END{ print $2 }') | $(date "+%b %d (%a) %I:%M%p") |" | tr "\n" " "
    sleep 1m
done
