#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources 
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi


if [ -f $sysmodmap ]; then 
	xmodmap $sysmodmap
fi


if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then 
	xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then 
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
 	done
	unset f
fi

xinput --set-prop 'BenQ ZOWIE BenQ ZOWIE Gaming Mouse' 'Device Accel Constant Deceleration' 1
synclient TapButton1=1
synclient MaxSpeed=2.5
synclient ClickFinger2=2
synclient ClickFinger3=3
synclient HorizTwoFingerScroll=1
xset m 1 0

setxkbmap -model pc105 -layout us,ru -variant dvorak-qwerty, -option "grp:ctrl_shift_toggle" -option "terminate:ctrl_alt_bksp"

exec dwm & dwmbar




